version: '3'

services:
  db:
    container_name: db
    image: postgres
  app:
    container_name: app
    build:
      context: ..
      dockerfile: ./config/Dockerfile
    entrypoint: /code/config/web.sh
    volumes:
      - ..:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
